# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5099b3f611e07bddb6493575672633329502f0e76eac48bc9507528a68062732d3d6d83742a7a5b3956f91b56818c91de5704f70cc014094fc148a3999a2f832

test:
  secret_key_base: 0198db5336c755e6824cc55247da098f56f67a354b7f7e831c7ef9bab5fdf0a563c117f49e8fc70893591287196ee121354b9fc599b9506bf372b9b57aa15ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
